### PR TITLE
Bangladesh,ireland,monaco,estonia

### PR DESCRIPTION
**Pull request by kamil-tekiela**
After the success of yesterday's PR, I looked at some of the more complicated borders. Generating Laos locations became a lot more accurate now. Previously, 50% of locations were in Thailand or Cambodia.

### CODE REVIEW

**Comment by tzhf** [comment]
Nice ! 
I just noticed that map-generator uses it's own json. It used to be this one but i did a few changes and they'e not in sync anymore.
I will make sure that both mapcheckr and map-generator use the same geojson

**Comment by tzhf** [comment]
Nice !
Just noticed that map-generator actually doesn't use this package as the implementation is slightly different. Also the geojsons are sligthly different (eg: far north Siberia or Alaska) to avoid generating in empty areas. 
But that's just a small difference, i can update it to use your json as base once you're done.

**Comment by kamil-tekiela** [comment]
That makes sense. I am filtering out the wrong locations, but I guess if the map generator's geojson could be updated too then it would be best.

**Comment by kamil-tekiela** [comment]
Although Alaska has official coverage in a number of towns in the West.

**Pull request merged**
